create table if not exists public.daily_reports (
  id bigint generated by default as identity primary key,
  report_date date not null unique,
  payload jsonb not null,
  sources jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.daily_reports enable row level security;

revoke all on table public.daily_reports from anon, authenticated;
grant select, insert, update on table public.daily_reports to service_role;
grant usage, select on sequence public.daily_reports_id_seq to service_role;

